# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nguyễn Đức Nhân
email: ducnhannguyen2410@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Mình chả biết ghi gì ở đây hết
url: "https://iambestfeeddddd.github.io/"
github_username: iambestfeeddddd
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes


# Outputting
permalink: /:year/:month/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Kathmandu

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Nguyễn Đức Nhân"
  avatar : "/images/bio-photo.jpg"
  bio    : "Research"
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/Amonnnnnn1"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/iambestfeeddddd"
#    - label: "Email"
#      icon: "fab fa-envelope"
#      url: "mailto:meamitkc@gmail.com"
#    - label: "Feed"
#      icon: "fab fa-fw fa-globe"
#      url: "/feed.xml"

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/Amonnnnnn1"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/iambestfeeddddd"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "images/"
    values:
      image: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
